global:
  frontOrigins: http://localhost:3000
  jwkSetUri: http://auth.auth-service.svc.cluster.local/oauth2/jwks
  kafka:
    server: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  services:
    webGateway:
      name: web-gateway
      namespace: web-gateway
      port: 80
    websocketService:
      name: websocket
      namespace: websocket-service
      port: 80
    jobService:
      name: job
      namespace: job-service
      ports:
        grpcPort: 9090
    userProfileService:
      name: user-profile
      namespace: user-profile-service
      ports:
        grpcPort: 9090
    userPreferenceService:
      name: user-preference
      namespace: user-preference-service
      ports:
        grpcPort: 9090
    organizationService:
      name: organization
      namespace: organization-service
      ports:
        grpcPort: 9090
    teamService:
      name: team
      namespace: team-service
      ports:
        grpcPort: 9090
    planService:
      name: plan
      namespace: plan-service
      ports:
        grpcPort: 9090
    storageService:
      name: storage
      namespace: storage-service
      ports:
        grpcPort: 9090

job-service:
  enabled: true
  replicaCount: 2
  javaOptions: "-XX:MaxDirectMemorySize=512M -XX:NativeMemoryTracking=detail -XX:MaxMetaspaceSize=256M -XX:+UseContainerSupport -XX:MaxRAMPercentage=80.0 -Xss512k"
  resources:
    requests:
      memory: "6Gi"
      cpu: "1.5"
    limits:
      memory: "6Gi"
      cpu: "1.5"
  tolerations:
    - key: "for"             
      operator: "Equal"      
      value: "tracking"  
      effect: "NoSchedule" 
  nodeSelector:
    for: "tracking"
  image:
    repository: ablankz/nova-job-service
    pullPolicy: IfNotPresent
    tag: "1.0.4-arm64"
  serviceAccount:
    name: "job-sa"
  db:
    url: "jdbc:postgresql://job-postgres-postgresql.job-service.svc.cluster.local:5432/job"
    username: postgres
    secretName: job-db-secrets
    secretPasswordKey: password
    maxPoolSize: "200"
    connectionTimeout: "60000"
    idleTimeout: "60000"
    maxLifetime: "1800000"
    leakDetectionThreshold: "60000"
  redis:
    host: job-redis-master.job-service.svc.cluster.local
    port: 6379
    secretName: job-redis-secrets
    secretPasswordKey: password
  secret:
    secretName: job-app-secrets
    secretPasswordKey: custom
  # autoscaling:
  #   enabled: true
  #   minReplicas: 1
  #   maxReplicas: 3
  #   targetCPUUtilizationPercentage: 80
  #   targetMemoryUtilizationPercentage: 75
  volumes:
  - name: job-app-secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "job-app-secrets"
  volumeMounts:
  - name: job-app-secrets-store
    mountPath: "/mnt/app-secrets-store"
    readOnly: true
  kafka:
    jobSubscribeSuccess: true
    jobSubscribeFailed: true
    jobSubscribeInitialized: true
    jobSubscribeProcessed: false