auth:
  enabled: true
  existingSecret: job-redis-secrets
  existingSecretPasswordKey: password
serviceAccount:
  create: false
master:
  serviceAccount:
    create: false
    name: job-sa
  persistence:
    enabled: true
    size: 8Gi
    storageClass: block-general
    accessModes: 
      - ReadWriteOnce
  service:
    ports:
      redis: 6379
  extraVolumes:
    - name: job-secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "job-redis-secrets"
  extraVolumeMounts:
    - name: job-secrets-store
      mountPath: "/mnt/secrets-store"
      readOnly: true
replica:
  replicaCount: 0