auth:
  enabled: true
  existingSecret: job-redis-secrets
  existingSecretPasswordKey: password
serviceAccount:
  create: false
master:
  resources:
    requests:
      memory: "10Gi"
      cpu: "1"
    limits:
      memory: "10Gi"
      cpu: "1"
  tolerations:
    - key: "for"             
      operator: "Equal"      
      value: "tracking"  
      effect: "NoSchedule" 
  nodeSelector:
    for: "tracking"
  serviceAccount:
    create: false
    name: job-sa
  persistence:
    enabled: true
    size: 8Gi
    storageClass: block-general
    accessModes: 
      - ReadWriteOnce
  service:
    ports:
      redis: 6379
  extraVolumes:
    - name: job-secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "job-redis-secrets"
  extraVolumeMounts:
    - name: job-secrets-store
      mountPath: "/mnt/secrets-store"
      readOnly: true
replica:
  replicaCount: 0