global:
  frontOrigins: http://localhost:3000
  jwkSetUri: http://auth.auth-service.svc.cluster.local/oauth2/jwks
  kafka:
    server: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  services:
    webGateway:
      name: web-gateway
      namespace: web-gateway
      port: 80
    websocketService:
      name: websocket
      namespace: websocket-service
      port: 80
    jobService:
      name: job
      namespace: job-service
      ports:
        grpcPort: 9090
    userProfileService:
      name: user-profile
      namespace: user-profile-service
      ports:
        grpcPort: 9090
    userPreferenceService:
      name: user-preference
      namespace: user-preference-service
      ports:
        grpcPort: 9090
    organizationService:
      name: organization
      namespace: organization-service
      ports:
        grpcPort: 9090
    teamService:
      name: team
      namespace: team-service
      ports:
        grpcPort: 9090
    planService:
      name: plan
      namespace: plan-service
      ports:
        grpcPort: 9090
    storageService:
      name: storage
      namespace: storage-service
      ports:
        grpcPort: 9090

websocket-service:
  enabled: true
  # replicaCount: 3
  resources:
    requests:
      memory: "1.5Gi"
      cpu: "400m"
    limits:
      memory: "2Gi"
      cpu: "1"
  image:
    repository: ablankz/nova-ws-service
    pullPolicy: IfNotPresent
    tag: "1.0.4"
  serviceAccount:
    name: "websocket-sa"
  db:
    url: "jdbc:postgresql://websocket-postgres-postgresql.websocket-service.svc.cluster.local:5432/websocket"
    username: svcuser
    secretName: websocket-db-secrets
    secretPasswordKey: password
  redis:
    host: websocket-redis-master.websocket-service.svc.cluster.local
    port: 6379
    secretName: websocket-redis-secrets
    secretPasswordKey: password
  secret:
    secretName: websocket-app-secrets
    secretPasswordKey: custom
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 75
  volumes:
  - name: websocket-app-secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "websocket-app-secrets"
  volumeMounts:
  - name: websocket-app-secrets-store
    mountPath: "/mnt/app-secrets-store"
    readOnly: true
  istio:
    enabled: true
    virtualServiceName: websocket
    namespace: istio-system
    hosts:
      - ws.state.api.cresplanex.org
    gateway: public-gateway