{
 "title": "App",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Whole CPU Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",job=\"kubelet\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Whole Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\",job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace) (container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",namespace!=\"kube-system\", image=~\"docker.io/ablankz/.*\",  image!=\"docker.io/ablankz/debezium:1.0.0\", job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",namespace!=\"kube-system\", image=~\"docker.io/ablankz/.*\",  image!=\"docker.io/ablankz/debezium:1.0.0\", job=\"kubelet\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\",namespace!=\"kube-system\", image=~\"docker.io/ablankz/.*\",  image!=\"docker.io/ablankz/debezium:1.0.0\", job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",namespace!=\"kube-system\", image=~\"docker.io/ablankz/.*\",  image!=\"docker.io/ablankz/debezium:1.0.0\", job=\"kubelet\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(namespace) (container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",namespace!=\"kube-system\", image=~\"docker.io/bitnami/postgresql:.*\", job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB CPU Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",namespace!=\"kube-system\", image=~\"docker.io/bitnami/postgresql:.*\",  image!=\"docker.io/ablankz/debezium:1.0.0\", job=\"kubelet\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\",namespace!=\"kube-system\", image=~\"docker.io/bitnami/postgresql:.*\",  image!=\"docker.io/ablankz/debezium:1.0.0\", job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Memory Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",namespace!=\"kube-system\", image=~\"docker.io/bitnami/postgresql:.*\", job=\"kubelet\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}