apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: auth-service
spec:
  containers:
  - name: test
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: auth-secrets-store
      mountPath: "/mnt/app-secrets-store"
      readOnly: true
  serviceAccountName: auth-sa
  volumes:
  - name: auth-secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "auth-app-secrets"

