apiVersion: v1
kind: Service
metadata:
  name: {{ include "job-service.name" . }}
  namespace: {{ .Values.global.services.jobService.namespace }}
  labels:
    {{- include "job-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.services.jobService.ports.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "job-service.selectorLabels" . | nindent 4 }}
