{{- if .Values.storageService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-storage-connector-config
  namespace: {{ .Values.storageService.namespace }}
data:
  connector-config.json: |
    {
      "name": "storage-{{ .Values.base.name }}",
      "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "tasks.max": "1",
        "database.hostname": "{{ .Values.storageService.database.hostname }}",
        "database.port": "{{ .Values.storageService.database.port }}",
        "database.user": "{{ .Values.storageService.database.username }}",
        "database.password": "@DATABASE_PASSWORD@",
        "database.dbname": "{{ .Values.storageService.database.dbname }}",
        "database.server.name": "storage-db",
        "table.include.list": "core.message",
        "topic.prefix": "storage",
        "plugin.name": "pgoutput",
        "slot.name": "debezium_storage_slot",
        "publication.name": "debezium_storage_publication",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "true",
        "value.converter.schemas.enable": "true",
        "transforms": "messaging",
        "transforms.messaging.type": "org.cresplanex.core.cdc.debezium.TransactionalMessaging"
      }
    }
---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-storage-register-connector
  namespace: {{ .Values.storageService.namespace }}
  labels:
    sidecar.istio.io/inject: "false"
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storageService.database.passwordSecrets }}
                  key: {{ .Values.storageService.database.passwordSecretKey }}
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until psql -h {{ .Values.storageService.database.hostname }} -U {{ .Values.storageService.database.username }} -d {{ .Values.storageService.database.dbname }} -c "SELECT 1;" > /dev/null 2>&1; do
                echo "PostgreSQL is not ready. Retrying in 5 seconds..."
                sleep 5
              done
              echo "PostgreSQL is ready."
      containers:
        - name: register-connector
          image: bitnami/minideb:latest
          serviceAccountName: {{ .Values.storageService.serviceAccount }}
          command:
            - sh
            - -c
            - |
              apt-get update && apt-get install -y curl jq && \
              echo "Replacing database password in connector config" && \
              REPLACE_PASSWORD=$(sed "s/@DATABASE_PASSWORD@/$PGPASSWORD/g" /app_scripts/connector-config.json) && \
              echo "Registering connector" && \
              curl -X POST -H "Content-Type: application/json" \
              --data "$REPLACE_PASSWORD" \
              http://{{ .Values.base.connector.connectHost }}:{{ .Values.base.connector.connectPort }}/connectors && \
              exit 0
          volumeMounts:
            - name: connector-config
              mountPath: /app_scripts
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storageService.database.passwordSecrets }}
                  key: {{ .Values.storageService.database.passwordSecretKey }}
      volumes:
        - name: connector-config
          configMap:
            name: {{ .Release.Name }}-storage-connector-config
      {{- if .Values.storageService.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.storageService.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.storageService.affinity }}
      affinity:
        {{- toYaml .Values.storageService.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.storageService.tolerations }}
      tolerations:
        {{- toYaml .Values.storageService.tolerations | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
{{- end }}