{{- if .Values.teamService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-team-connector-config
  namespace: {{ .Values.teamService.namespace }}
data:
  connector-config.json: |
    {
      "name": "team-{{ .Values.base.name }}",
      "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "tasks.max": "1",
        "database.hostname": "{{ .Values.teamService.database.hostname }}",
        "database.port": "{{ .Values.teamService.database.port }}",
        "database.user": "{{ .Values.teamService.database.username }}",
        "database.password": "@DATABASE_PASSWORD@",
        "database.dbname": "{{ .Values.teamService.database.dbname }}",
        "database.server.name": "team-db",
        "table.include.list": "core.message",
        "topic.prefix": "team",
        "plugin.name": "pgoutput",
        "slot.name": "debezium_team_slot",
        "publication.name": "debezium_team_publication",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "true",
        "value.converter.schemas.enable": "true",
        "transforms": "messaging",
        "transforms.messaging.type": "org.cresplanex.core.cdc.debezium.TransactionalMessaging"
      }
    }
---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-team-register-connector
  namespace: {{ .Values.teamService.namespace }}
  labels:
    sidecar.istio.io/inject: "false"
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.teamService.database.passwordSecrets }}
                  key: {{ .Values.teamService.database.passwordSecretKey }}
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until psql -h {{ .Values.teamService.database.hostname }} -U {{ .Values.teamService.database.username }} -d {{ .Values.teamService.database.dbname }} -c "SELECT 1;" > /dev/null 2>&1; do
                echo "PostgreSQL is not ready. Retrying in 5 seconds..."
                sleep 5
              done
              echo "PostgreSQL is ready."
      containers:
        - name: register-connector
          image: bitnami/minideb:latest
          serviceAccountName: {{ .Values.teamService.serviceAccount }}
          command:
            - sh
            - -c
            - |
              apt-get update && apt-get install -y curl jq && \
              echo "Replacing database password in connector config" && \
              REPLACE_PASSWORD=$(sed "s/@DATABASE_PASSWORD@/$PGPASSWORD/g" /app_scripts/connector-config.json) && \
              echo "Registering connector" && \
              curl -X POST -H "Content-Type: application/json" \
              --data "$REPLACE_PASSWORD" \
              http://{{ .Values.base.connector.connectHost }}:{{ .Values.base.connector.connectPort }}/connectors && \
              exit 0
          volumeMounts:
            - name: connector-config
              mountPath: /app_scripts
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.teamService.database.passwordSecrets }}
                  key: {{ .Values.teamService.database.passwordSecretKey }}
      volumes:
        - name: connector-config
          configMap:
            name: {{ .Release.Name }}-team-connector-config
      {{- if .Values.teamService.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.teamService.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.teamService.affinity }}
      affinity:
        {{- toYaml .Values.teamService.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.teamService.tolerations }}
      tolerations:
        {{- toYaml .Values.teamService.tolerations | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
{{- end }}