namespace: auth-service
name: auth
app:
  secretName: auth-app-secrets
  secretPasswordKey: custom
  jwt:
    secretName: auth-app-secrets
    secretPasswordKey: jwt
serviceAccount:
  name: auth-sa
  javaOptions: "-XX:MaxDirectMemorySize=512M -XX:NativeMemoryTracking=detail -XX:MaxMetaspaceSize=256M -XX:+UseContainerSupport -XX:MaxRAMPercentage=80.0 -Xss512k"
image:
  tag: "1.0.5-arm64"
db:
  url: "jdbc:postgresql://auth-postgres-postgresql.auth-service.svc.cluster.local:5432/auth"
  username: postgres
  secretName: auth-db-secrets
  secretPasswordKey: password
  maxPoolSize: "40"
  connectionTimeout: "60000"
  idleTimeout: "60000"
  maxLifetime: "1800000"
  leakDetectionThreshold: "60000"
redis:
  host: auth-redis-master.auth-service.svc.cluster.local
  port: 6379
  secretName: auth-redis-secrets
  secretPasswordKey: password
kafka:
  server: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
istio:
  enabled: true
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "500m"
tolerations:
  - key: "for"             
    operator: "Equal"      
    value: "auth"      
    effect: "NoSchedule" 
nodeSelector:
  for: "auth"
volumes:
  - name: auth-app-secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "auth-app-secrets"
volumeMounts:
  - name: auth-app-secrets-store
    mountPath: "/mnt/app-secrets-store"
    readOnly: true
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75