namespace: auth-service
name: auth
app:
  secretName: auth-app-secrets
  secretPasswordKey: custom
  jwt:
    secretName: auth-app-secrets
    secretPasswordKey: jwt
serviceAccount:
  name: auth-sa
javaOptions: "-XX:MaxDirectMemorySize=256M"
image:
  tag: "1.0.4"
db:
  url: "jdbc:postgresql://auth-postgres-postgresql.auth-service.svc.cluster.local:5432/auth"
  username: svcuser
  secretName: auth-db-secrets
  secretPasswordKey: password
redis:
  host: auth-redis-master.auth-service.svc.cluster.local
  port: 6379
  secretName: auth-redis-secrets
  secretPasswordKey: password
kafka:
  server: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
istio:
  enabled: true
resources:
  requests:
    memory: "1.5Gi"
    cpu: "250m"
  limits:
    memory: "1.5Gi"
    cpu: "1"
volumes:
  - name: auth-app-secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "auth-app-secrets"
volumeMounts:
  - name: auth-app-secrets-store
    mountPath: "/mnt/app-secrets-store"
    readOnly: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75