namespace: auth-service
name: auth
app:
  secretName: auth-app-secrets
  secretPasswordKey: custom
  jwt:
    secretName: auth-app-secrets
    secretPasswordKey: jwt
serviceAccount:
  name: auth-sa
image:
  tag: "1.0.2"
db:
  url: "jdbc:postgresql://auth-postgres-postgresql.auth-service.svc.cluster.local:5432/auth"
  username: svcuser
  secretName: auth-db-secrets
  secretPasswordKey: password
redis:
  host: auth-redis-master.auth-service.svc.cluster.local
  port: 6379
  secretName: auth-redis-secrets
  secretPasswordKey: password
kafka:
  server: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
istio:
  enabled: true

volumes:
  - name: auth-app-secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "auth-app-secrets"

volumeMounts:
  - name: auth-app-secrets-store
    mountPath: "/mnt/app-secrets-store"
    readOnly: true