auth:
  enabled: true
  existingSecret: auth-redis-secrets
  existingSecretPasswordKey: password
serviceAccount:
  create: false
master:
  resources:
    requests:
      memory: "800Mi"
      cpu: "400m"
    limits:
      memory: "800Mi"
      cpu: "400m"
  tolerations:
    - key: "for"             
      operator: "Equal"      
      value: "auth"      
      effect: "NoSchedule" 
  nodeSelector:
    for: "auth"
  serviceAccount:
    create: false
    name: auth-sa
  persistence:
    enabled: true
    size: 8Gi
    storageClass: block-general
    accessModes: 
      - ReadWriteOnce
  service:
    ports:
      redis: 6379
  extraVolumes:
    - name: auth-secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "auth-redis-secrets"
  extraVolumeMounts:
    - name: auth-secrets-store
      mountPath: "/mnt/secrets-store"
      readOnly: true
replica:
  replicaCount: 0