apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-profile-service.name" . }}
  namespace: {{ .Values.global.services.userProfileService.namespace }}
  labels:
    {{- include "user-profile-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.services.userProfileService.ports.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "user-profile-service.selectorLabels" . | nindent 4 }}
