helmDefaults:
  wait: true
  timeout: 600
  # atomic: true       # インストール失敗時に自動ロールバック
  # concurrent: 1      # 同時実行数を1に制限

repositories:
  - name: ecr
    url: '{{ requiredEnv "AWS_ACCOUNT_ID" }}.dkr.ecr.{{ requiredEnv "AWS_REGION" }}.amazonaws.com'
    oci: true
    username: 'AWS'
    password: '{{ requiredEnv "ECR_PASSWORD" }}'

releases:
  - name: debezium-connector
    chart: ecr/debezium-connector
    version: 0.1.22
    values:
      - "connector-values.yaml"
