helmDefaults:
  wait: true
  timeout: 600
  # atomic: true       # インストール失敗時に自動ロールバック
  # concurrent: 1      # 同時実行数を1に制限

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: auth-redis
    namespace: auth-service
    chart: bitnami/redis
    values:
      - "auth/redis-values.yaml"
  - name: auth-postgres
    namespace: auth-service
    chart: bitnami/postgresql
    values:
      - global:
          postgresql:
            auth:
              password: '{{ env "ORIGIN_AUTH_PASSWORD" }}'
      - "auth/postgres-values.yaml"
  # - name: websocket-redis
  #   namespace: websocket-service
  #   chart: bitnami/redis
  #   values:
  #     - "websocket/redis-values.yaml"
  # - name: websocket-postgres
  #   namespace: websocket-service
  #   chart: bitnami/postgresql
  #   values:
  #       - global:
  #         postgresql:
  #           auth:
  #             password: '{{ env "ORIGIN_WEBSOCKET_PASSWORD" }}'
  #       - "websocket/postgres-values.yaml"
  - name: job-redis
    namespace: job-service
    chart: bitnami/redis
    values:
      - "job/redis-values.yaml"
  - name: job-postgres
    namespace: job-service
    chart: bitnami/postgresql
    values:
      - global:
          postgresql:
            auth:
              password: '{{ env "ORIGIN_JOB_PASSWORD" }}'
      - "job/postgres-values.yaml"
  - name: user-profile-postgres
    namespace: user-profile-service
    chart: bitnami/postgresql
    values:
      - global:
          postgresql:
            auth:
              password: '{{ env "ORIGIN_USER_PROFILE_PASSWORD" }}'
      - "user-profile/postgres-values.yaml"
  - name: user-preference-postgres
    namespace: user-preference-service
    chart: bitnami/postgresql
    values:
      - global:
          postgresql:
            auth:
              password: '{{ env "ORIGIN_USER_PREFERENCE_PASSWORD" }}'
      - "user-preference/postgres-values.yaml"
  - name: organization-postgres
    namespace: organization-service
    chart: bitnami/postgresql
    values:
      - global:
          postgresql:
            auth:
              password: '{{ env "ORIGIN_ORGANIZATION_PASSWORD" }}'
      - "organization/postgres-values.yaml"
  - name: team-postgres
    namespace: team-service
    chart: bitnami/postgresql
    values:
      - global:
          postgresql:
            auth:
              password: '{{ env "ORIGIN_TEAM_PASSWORD" }}'
      - "team/postgres-values.yaml"
  - name: storage-postgres
    namespace: storage-service
    chart: bitnami/postgresql
    values:
      - global:
          postgresql:
            auth:
              password: '{{ env "ORIGIN_STORAGE_PASSWORD" }}'
      - "storage/postgres-values.yaml"
  - name: plan-postgres
    namespace: plan-service
    chart: bitnami/postgresql
    values:
      - global:
          postgresql:
            auth:
              password: '{{ env "ORIGIN_PLAN_PASSWORD" }}'
      - "plan/postgres-values.yaml"
