helmDefaults:
  wait: true
  timeout: 600
  # atomic: true       # インストール失敗時に自動ロールバック
  # concurrent: 1      # 同時実行数を1に制限

repositories:
  - name: ecr
    url: '{{ requiredEnv "AWS_ACCOUNT_ID" }}.dkr.ecr.{{ requiredEnv "AWS_REGION" }}.amazonaws.com'
    oci: true
    username: 'AWS'
    password: '{{ requiredEnv "ECR_PASSWORD" }}'

releases:
  - name: auth
    namespace: auth-service
    chart: ecr/auth-server
    version: 0.1.10
    values:
      - "auth/app-values.yaml"
  - name: job-service
    namespace: job-service
    chart: ecr/job-stack
    version: 0.1.7
    values:
      - "job/app-values.yaml"
    needs:
      - auth-service/auth
  - name: service
    chart: ecr/services-chart
    version: 0.1.7
    values:
      - "service-value.yaml"
    needs:
      - job-service/job-service
  - name: gateway
    chart: ecr/gateway-stack
    version: 0.1.7
    values:
      - "gateway/app-values.yaml"
    needs:
      - service
  # - name: websocket
  #   chart: ecr/websocket-stack
  #   version: 0.1.1
  #   values:
  #     - "websocket/app-values.yaml"
  #   needs:
  #     - service
