apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-server.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: REQUIRE_HTTPS
              value: "false"
            - name: AUTH_SEVER_PORT
              value: "{{ .Values.containerPort }}"
            - name: DB_URL
              value: "{{ .Values.db.url }}"
            - name: DB_USERNAME
              value: "{{ .Values.db.username }}"
            - name: REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: KAFKA_SERVER
              value: "{{ .Values.kafka.server }}"
            - name: CUSTOM_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secretName }}
                  key: {{ .Values.app.secretPasswordKey }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.jwt.secretName }}
                  key: {{ .Values.app.jwt.secretPasswordKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: {{ .Values.db.secretPasswordKey }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: {{ .Values.redis.secretPasswordKey }}
            - name: DB_MAX_POOL_SIZE
              value: "{{ .Values.db.maxPoolSize }}"
            - name: DB_CONNECTION_TIMEOUT
              value: "{{ .Values.db.connectionTimeout }}"
            - name: DB_IDLE_TIMEOUT
              value: "{{ .Values.db.idleTimeout }}"
            - name: DB_MAX_LIFETIME
              value: "{{ .Values.db.maxLifetime }}"
            - name: DB_LEAK_DETECTION_THRESHOLD
              value: "{{ .Values.db.leakDetectionThreshold }}"
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.javaOptions }}"
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}