{{- if .Values.kafkaConnect.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafkaConnect.name }}
  namespace: {{ .Values.base.namespace.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafkaCluster.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.kafkaConnect.name }}
      app.kubernetes.io/instance: "{{ .Values.kafkaConnect.name }}-connect"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.kafkaConnect.name }}
        app.kubernetes.io/instance: "{{ .Values.kafkaConnect.name }}-connect"
    spec:
      containers:
        - name: connect
          image: "{{ .Values.kafkaConnect.image.repository }}:{{ .Values.kafkaConnect.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaConnect.image.pullPolicy }}
          ports:
            - containerPort: 8083
              name: connect-port
          env:
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.kafkaConnect.bootstrapServers }}
            - name: GROUP_ID
              value: "{{ .Values.kafkaConnect.config.group_id }}"
            - name: CONFIG_STORAGE_TOPIC
              value: "{{ .Values.kafkaConnect.config.config_storage_topic }}"
            - name: OFFSET_STORAGE_TOPIC
              value: "{{ .Values.kafkaConnect.config.offset_storage_topic }}"
            - name: STATUS_STORAGE_TOPIC
              value: "{{ .Values.kafkaConnect.config.status_storage_topic }}"
            {{- range .Values.kafkaConnect.additionalEnv }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.kafkaConnect.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.kafkaConnect.volumeMounts | nindent 12 }}
      {{- with .Values.kafkaConnect.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafkaConnect.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafkaConnect.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafkaConnect.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafkaConnect.name }}
  namespace: {{ .Values.base.namespace.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafkaCluster.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kafkaConnect.port }}
      targetPort: connect-port
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.kafkaConnect.name }}
    app.kubernetes.io/instance: "{{ .Values.kafkaConnect.name }}-connect"
{{- end }}

