apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-db-secrets
  namespace: auth-service
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "auth-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "postgresAdminPassword"
            objectAlias: "postgres-admin-password"
          - path: "postgresPassword"
            objectAlias: "postgres-password"
  secretObjects:
    - secretName: auth-db-secrets # k8s上のSecret名
      type: Opaque
      data:
        - objectName: "postgres-admin-password"
          key: "admin-password"
        - objectName: "postgres-password"
          key: "password"

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-redis-secrets
  namespace: auth-service
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "auth-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "redisPassword"
            objectAlias: "redis-password"
  secretObjects:
    - secretName: auth-redis-secrets
      type: Opaque
      data:
        - objectName: "redis-password"
          key: "password"

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-app-secrets
  namespace: auth-service
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "auth-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "appCustomSecret"
            objectAlias: "app-custom-secret"
          - path: "appJwtSecret"
            objectAlias: "app-jwt-secret"
  secretObjects:
    - secretName: auth-app-secrets
      type: Opaque
      data:
        - objectName: "app-custom-secret"
          key: "custom"
        - objectName: "app-jwt-secret"
          key: "jwt"