apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: user-profile-db-secrets
  namespace: user-profile-service
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "user-profile-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "postgresAdminPassword"
            objectAlias: "postgres-admin-password"
          - path: "postgresPassword"
            objectAlias: "postgres-password"
  secretObjects:
    - secretName: user-profile-db-secrets # k8s上のSecret名
      type: Opaque
      data:
        - objectName: "postgres-admin-password"
          key: "admin-password"
        - objectName: "postgres-password"
          key: "password"

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: user-profile-app-secrets
  namespace: user-profile-service
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "user-profile-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "appCustomSecret"
            objectAlias: "app-custom-secret"
  secretObjects:
    - secretName: user-profile-app-secrets
      type: Opaque
      data:
        - objectName: "app-custom-secret"
          key: "custom"