base:
  name: "debezium-connector"
  connector:
    connectHost: "debezium-connector-connect"
    connectPort: 8083
authServer:
  enabled: true
  namespace: "auth-service"
  serviceAccount: "auth"
  volumeMounts:
  nodeSelector: {}
  affinity: {}
  tolerations: []
  database:
    hostname: "postgres"
    port: 5432
    username: "postgres"
    dbname: "auth"
    passwordSecrets: "auth-secrets"
    passwordSecretKey: "password"
jobService:
  enabled: true
  namespace: "job-service"
  serviceAccount: "job"
  volumeMounts:
    - name: "auth-postgres"
      mountPath: "/var/lib/postgresql/data"
    - name: "auth-postgres-wal"
      mountPath: "/var/lib/postgresql/wal"
  nodeSelector: {}
  affinity: {}
  tolerations: []
  database:
    hostname: "postgres"
    port: 5432
    username: "postgres"
    dbname: "job"
    passwordSecrets: "job-secrets"
    passwordSecretKey: "password"
websocketService:
  enabled: true
  namespace: "websocket-service"
  serviceAccount: "websocket"
  volumeMounts: []
  nodeSelector: {}
  affinity: {}
  tolerations: []
  database:
    hostname: "postgres"
    port: 5432
    username: "postgres"
    dbname: "websocket"
    passwordSecrets: "websocket-secrets"
    passwordSecretKey: "password"
userProfileService:
  enabled: true
  namespace: "user-profile-service"
  serviceAccount: "user-profile"
  volumeMounts: []
  nodeSelector: {}
  affinity: {}
  tolerations: []
  database:
    hostname: "postgres"
    port: 5432
    username: "postgres"
    dbname: "user_profile"
    passwordSecrets: "user-profile-secrets"
    passwordSecretKey: "password"
userPreferenceService:
  enabled: true
  namespace: "user-preference-service"
  serviceAccount: "user-preference"
  volumeMounts: []
  nodeSelector: {}
  affinity: {}
  tolerations: []
  database:
    hostname: "postgres"
    port: 5432
    username: "postgres"
    dbname: "user_preference"
    passwordSecrets: "user-preference-secrets"
    passwordSecretKey: "password"
organizationService:
  enabled: true
  namespace: "organization-service"
  serviceAccount: "organization"
  volumeMounts: []
  nodeSelector: {}
  affinity: {}
  tolerations: []
  database:
    hostname: "postgres"
    port: 5432
    username: "postgres"
    dbname: "organization"
    passwordSecrets: "organization-secrets"
    passwordSecretKey: "password"
teamService:
  enabled: true
  namespace: "team-service"
  volumeMounts: []
  serviceAccount: "team"
  nodeSelector: {}
  affinity: {}
  tolerations: []
  database:
    hostname: "postgres"
    port: 5432
    username: "postgres"
    dbname: "team"
    passwordSecrets: "team-secrets"
    passwordSecretKey: "password"
planService:
  enabled: true
  namespace: "plan-service"
  serviceAccount: "plan"
  volumeMounts: []
  nodeSelector: {}
  affinity: {}
  tolerations: []
  database:
    hostname: "postgres"
    port: 5432
    username: "postgres"
    dbname: "plan"
    passwordSecrets: "plan-secrets"
    passwordSecretKey: "password"
storageService:
  enabled: true
  namespace: "storage-service"
  serviceAccount: "storage"
  volumeMounts: []
  nodeSelector: {}
  affinity: {}
  tolerations: []
  database:
    hostname: "postgres"
    port: 5432
    username: "postgres"
    dbname: "storage"
    passwordSecrets: "storage-secrets"
    passwordSecretKey: "password"